/*
 * EDIT THIS FILE - it is NOT generated by Glade.
 */

#include <gnome.h>
#include <glade/glade.h>

/*
 * Given a name of a widget, instantiate it.  Assume the widget is
 * in a glade file located at %TERRAFORM_DATA_DIR%/glade/<widget_name>.glade
 */
static GtkWidget *
create_widget (const char *name)
{
  gchar     *filename;
  GladeXML  *xml;
  GtkWidget *widget;

  /* FIXME: Also check in $(HOME)/.terraform/glade for home installations. */
  filename = g_strdup_printf (TERRAFORM_DATA_DIR "/glade/%s.glade", name);
  xml = glade_xml_new (filename, NULL, NULL);
  g_free (filename);

  glade_xml_signal_autoconnect (xml);
  widget = glade_xml_get_widget (xml, name);
/*  g_object_unref (G_OBJECT (xml)); */

  return widget;
}

GtkWidget *
create_main_window (void)
{
  return create_widget ("main_window");
}

GtkWidget *
create_about_window (void)
{
  return create_widget ("about_window");
}

GtkWidget *
create_spectral_window (void)
{
  return create_widget ("spectral_window");
}

GtkWidget *
create_perlin_noise_window (void)
{
  return create_widget ("perlin_noise_window");
}

GtkWidget *
create_subdivision_window (void)
{
  return create_widget ("subdivision_window");
}

GtkWidget *
create_open_file (void)
{
  return create_widget ("open_file");
}

GtkWidget *
create_terrain_window (void)
{
  return create_widget ("terrain_window");
}

GtkWidget *
create_level_connector_window (void)
{
  return create_widget ("level_connector_window");
}

GtkWidget *
create_craters_window (void)
{
  return create_widget ("craters_window");
}

GtkWidget *
create_fill_window (void)
{
  return create_widget ("fill_window");
}

GtkWidget *
create_fold_window (void)
{
  return create_widget ("fold_window");
}

GtkWidget *
create_gaussian_hill_window (void)
{
  return create_widget ("gaussian_hill_window");
}

GtkWidget *
create_radial_scale_window (void)
{
  return create_widget ("radial_scale_window");
}

GtkWidget *
create_mirror_window (void)
{
  return create_widget ("mirror_window");
}

GtkWidget *
create_options_window (void)
{
  return create_widget ("options_window");
}

GtkWidget *
create_find_povray_window (void)
{
  return create_widget ("find_povray_window");
}

GtkWidget *
create_rotate_window (void)
{
  return create_widget ("rotate_window");
}

GtkWidget *
create_roughen_window (void)
{
  return create_widget ("roughen_window");
}

GtkWidget *
create_smooth_window (void)
{
  return create_widget ("smooth_window");
}

GtkWidget *
create_terrace_window (void)
{
  return create_widget ("terrace_window");
}

GtkWidget *
create_tile_window (void)
{
  return create_widget ("tile_window");
}

GtkWidget *
create_erode_window (void)
{
  return create_widget ("erode_window");
}

GtkWidget *
create_flowmap_window (void)
{
  return create_widget ("flowmap_window");
}

GtkWidget *
create_scale_window (void)
{
  return create_widget ("radial_scale_window");
}

GtkWidget *
create_save_as (void)
{
  return create_widget ("save_as");
}

GtkWidget *
create_preview_popup (void)
{
  return create_widget ("preview_popup");
}

GtkWidget *
create_undo_tree_window (void)
{
  return create_widget ("undo_tree_window");
}

GtkWidget *
create_execution_error_window (void)
{
  return create_widget ("execution_error_window");
}

GtkWidget *
create_merge_window (void)
{
  return create_widget ("merge_window");
}

GtkWidget *
create_native_render_window (void)
{
  return create_widget ("native_render_window");
}

GtkWidget *
create_move_window (void)
{
  return create_widget ("move_window");
}

GtkWidget *
create_print_preview_window (void)
{
  return create_widget ("print_preview_window");
}

GtkWidget *
create_select_by_height_window (void)
{
  return create_widget ("select_by_height_window");
}

GtkWidget *
create_feather_window (void)
{
  return create_widget ("feather_window");
}

GtkWidget *
create_place_objects_window (void)
{
  return create_widget ("place_objects_window");
}

GtkWidget *
create_transform_window (void)
{
  return create_widget ("transform_window");
}

GtkWidget *
create_file_options_window (void)
{
  return create_widget ("file_options_window");
}

GtkWidget *
create_export_view_window (void)
{
  return create_widget ("export_view_window");
}

GtkWidget *
create_chooser_window (void)
{
  return create_widget ("chooser_window");
}

GtkWidget *
create_faulting_window (void)
{
  return create_widget ("faulting_window");
}

GtkWidget *
create_info_window (void)
{
  return create_widget ("info_window");
}

GtkWidget *
create_close_terrain_dialog (void)
{
  return create_widget ("close_terrain_dialog");
}

GtkWidget *
create_join_window (void)
{
  return create_widget ("join_window");
}

GtkWidget *
create_digital_filter_window (void)
{
  return create_widget ("digital_filter_window");
}

GtkWidget *
create_close_terraform_dialog (void)
{
  return create_widget ("close_terraform_dialog");
}

GtkWidget *
create_erode_flowmap_window (void)
{
  return create_widget ("erode_flowmap_window");
}

GtkWidget *
create_rasterize_window (void)
{
  return create_widget ("rasterize_window");
}

GtkWidget *
create_warp_window (void)
{
  return create_widget ("warp_window");
}

GtkWidget *
create_error_log_filesel (void)
{
  return create_widget ("error_log_filesel");
}

GtkWidget *
create_spherical_map_window (void)
{
  return create_widget ("spherical_map_window");
}

GtkWidget *
create_basins_window (void)
{
  return create_widget ("basins_window");
}

GtkWidget *
create_rescale_placed_objects_window (void)
{
  return create_widget ("rescale_placed_objects_window");
}

GtkWidget *
create_terrain_options_window (void)
{
  return create_widget ("terrain_options_window");
}

GtkWidget *
create_scene_options_window (void)
{
  return create_widget ("scene_options_window");
}

GtkWidget *
create_povray_render_options_window (void)
{
  return create_widget ("povray_render_options_window");
}

GtkWidget *
create_prune_window (void)
{
  return create_widget ("prune_window");
}

GtkWidget *
create_river_window (void)
{
  return create_widget ("river_window");
}

GtkWidget *
create_river_all_window (void)
{
  return create_widget ("river_all_window");
}

GtkWidget *
create_installer_window (void)
{
  return create_widget ("installer_window");
}

GtkWidget *
create_trace_objects_window (void)
{
  return create_widget ("trace_objects_window");
}
